<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\RouterController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Http\Request;

Route::get('/', [RouterController::class, 'index'])->name('welcome'); // Route for the home page

// Authentication routes (generated by php artisan make:auth)
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Custom registration routes (if you need them - otherwise, Auth::routes() handles it)
Route::get('/register', [AuthController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [AuthController::class, 'register']);

// Custom login routes (if you need them - otherwise, Auth::routes() handles it)
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/config/router', [RouterController::class, 'showConfigForm'])->name('router.config.form');


Route::middleware('auth')->group(function () {
    Route::get('/config/router', [RouterController::class, 'showConfigForm'])->name('router.config.form');
    Route::post('/config/router', [RouterController::class, 'updateConfig'])->name('router.config.update');
    Route::get('/dashboard', function () {
        return view('dashboard');
    });

    //  Probably don't need this:
    //Route::get('/config', [RouterController::class, 'index']); //Unreachable code
});

Route::get('/ssh/reboot', [RouterController::class, 'ssh'])->name('router.ssh.reboot'); //Reboot do not needs auth
